Algoritmo "ex64"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara (GOAT)
// Descrição   : Mostrar uma contagem de 0 a 40 com o incremento de 5
// Autor(a)    : Felipe
// Data atual  : 29/01/2026
Var
   // Seção de Declarações das variáveis
   C: inteiro
   
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   
   Para C <- 0 ate 40 passo 5 faca
        Escreva (C)
   FimPara
   Escreval (" Acabou!")

Fimalgoritmo
