Algoritmo "ex65"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara (GOAT)
// Descrição   : Mostrar uma contagem de 100 até 0 com o decremento de 10
// Autor(a)    : Felipe
// Data atual  : 29/01/2026
Var
   // Seção de Declarações das variáveis
   C: inteiro
   
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   
   Para C <- 100 ate 0 passo -10 faca
        Escreva (C)
   FimPara
   Escreva (" Acabou!")

Fimalgoritmo
