Algoritmo "ex2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara (GOAT)
// Descrição   : Ler o nome de uma mensagem e mostrar uma mensagem de boas vindas
// Autor(a)    : Felipe
// Data atual  : 18/01/2026
Var
// Seção de Declarações das variáveis
   N: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva ("Escreva o seu nome: ")
   leia (N)
   
   escreva ("Olá, ",N,", Bem-vindo!")


Fimalgoritmo